### ISSUE TITLE
Getting "java.lang.ClassCastException: graphql.schema.GraphQLArgument cannot be cast to graphql.schema.GraphQLInputObjectField"

### ISSUE THREAD

**Issue by hannesj** [andimarek/graphql-java#10]
Hi,

I'm getting multiple exceptions when running the [GraphQL introspection query](https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js) on my schema.

Stack trace is as follows:
```
15:49:11.335 INFO (Execution.java:134) Exception while fetching data
java.lang.ClassCastException: graphql.schema.GraphQLArgument cannot be cast to graphql.schema.GraphQLInputObjectField
    at graphql.introspection.Introspection$2.get(Introspection.java:87) ~[graphql-java-2015-08-16T21-37-10.jar:na]
    at graphql.execution.Execution.resolveField(Execution.java:132) [graphql-java-2015-08-16T21-37-10.jar:na]
    at graphql.execution.Execution.access$000(Execution.java:26) [graphql-java-2015-08-16T21-37-10.jar:na]
    at graphql.execution.Execution$1.call(Execution.java:97) [graphql-java-2015-08-16T21-37-10.jar:na]
```

The easiest way to replicate is to run [GraphIndexTest#testGraphQLIntrospectionQuery](https://github.com/hannesj/OpenTripPlanner/blob/graphql/src/test/java/org/opentripplanner/routing/graph/GraphIndexTest.java#L131) from [this branch](https://github.com/hannesj/OpenTripPlanner/tree/graphql)

**Comment by andimarek** [comment]
I added a Bugfix. Could you please try it with latest version '2015-08-18T16-47-45'?

**Comment by hannesj** [comment]
Thanks, seems to work now!
