### ISSUE TITLE
Compilation error: cannot implement get(DataFetchingEnvironment) in DataFetcher

### ISSUE THREAD

**Issue by testower** [andimarek/graphql-java#12]
I'm trying to implement a simple DataFetcher and getting a compilation error.

The following is given as an argument to a field definition builder call to ```dataFetcher()```.

```java
new DataFetcher() {
  @Override
  Object get(DataFetchingEnvironment environment) {
    // some code returning an Object
  }
}
```

The compilation error is:

```shell
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project rest: Compilation failure
[ERROR] <path>/GraphQueryResource.java:[95,15] error: get(DataFetchingEnvironment) in <anonymous <package>.GraphQueryResource$1> cannot implement get(DataFetchingEnvironment) in DataFetcher
```
A more complete stack trace: 

```shell
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project rest: Compilation failure
[ERROR] <path>/GraphQueryResource.java:[95,15] error: get(DataFetchingEnvironment) in <anonymous <package>.GraphQueryResource$1> cannot implement get(DataFetchingEnvironment) in DataFetcher
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project rest: Compilation failure
<path>/GraphQueryResource.java:[95,15] error: get(DataFetchingEnvironment) in <anonymous <package>.GraphQueryResource$1> cannot implement get(DataFetchingEnvironment) in DataFetcher


        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
<path>/GraphQueryResource.java:[95,15] error: get(DataFetchingEnvironment) in <anonymous <package>.GraphQueryResource$1> cannot implement get(DataFetchingEnvironment) in DataFetcher


        at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:516)
        at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:114)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :rest
```

Someone advised me to delete the user's ```.m2``` folder, but that didn't help in my case.

Any ideas about what could be causing this?

**Comment by andimarek** [comment]
Your get Method must be public, because it implements a Interface Method, which are always public.

So please try this:

```java
new DataFetcher() {
  @Override
public Object get(DataFetchingEnvironment environment) {
    // some code returning an Object
  }
}```

The example in the README makes the same mistake ... I will update it. Thanks for reporting!

**Comment by testower** [comment]
Brilliant! Thanks didn't notice that one.
