### ISSUE TITLE
Trouble with UnmodifiedType and TypeReference

### ISSUE THREAD

**Issue by raptortech-js** [andimarek/graphql-java#38]
My schema has a circular link, and I plan to add many more, but I seem to be getting into a lot of trouble. In my schema, which is a GraphQL translation of the Tumblr API, based on the Jumblr client, you can get the `Post`s on a `Blog`, and the `Note`s on a `Post`, and the `Blog` that was the source of each `Note`. When I build the schema, I use direct `GraphQLObjectType`s whenever possible, and `GraphQLTypeReference`s whenever not. I'm pretty sure this is the correct way to do this, as it's what's done in the Garfield schema sample. I seem to be running into trouble with the schema validator, which is not expecting type references. In fact, I wasn't expecting type references to be in the schema either, as the docs state that a type reference is "replaced with the real type object when the schema is build [sic]." When I build the schema, though, I clearly still have type references in there. I know because when I run `System.out.println(((GraphQLObjectType) schema.getType("Note")).getFieldDefinition("blog").getType().getClass())`, I get `class graphql.schema.GraphQLTypeReference`.

Here's the full stack trace:

```
[main] INFO graphql.GraphQL - Executing request. operation name: null. Request: {blog(blogName: "yo-fuckers") {name, posts(limit: "1", id: "125493544279") {id, notes {type, blog {name}}}}} 
Exception in thread "main" java.lang.ClassCastException: graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLUnmodifiedType
	at graphql.schema.SchemaUtil.getUnmodifiedType(SchemaUtil.java:34)
	at graphql.schema.SchemaUtil.isLeafType(SchemaUtil.java:16)
	at graphql.validation.rules.ScalarLeafs.checkField(ScalarLeafs.java:21)
	at graphql.validation.RulesVisitor.checkField(RulesVisitor.java:92)
	at graphql.validation.RulesVisitor.enter(RulesVisitor.java:51)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:19)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverse(LanguageTraversal.java:14)
	at graphql.validation.Validator.validateDocument(Validator.java:20)
	at graphql.GraphQL.execute(GraphQL.java:73)
	at graphql.GraphQL.execute(GraphQL.java:55)
	at graphql.GraphQL.execute(GraphQL.java:47)
	at App.graphQLTest(App.java:81)
	at App.main(App.java:43)
```

**Comment by raptortech-js** [comment]
Ah-ha! Turns out I was never adding these types to the type dictionary when I built the schema, and I was relying on the fact that a type that explicitly points to another type will automatically include that other type in the resulting schema, and but references won't get replaced.
