### ISSUE TITLE
Enum Value cannot be optional in mutation input object

### ISSUE THREAD

**Issue by kristofdepypere** [andimarek/graphql-java#71]
When doing a relay-like mutation, Enums cannot be optional. Suppose you trigger the following mutation;

```
mutation ChangeFriend(\$input:ChangeFriendRequest) {
                changeFriend(input:\$input) {
                    clientMutationId
                }
            }
```

ChangeFriendRequest has following schema:

```
{
          "kind": "INPUT_OBJECT",
          "name": "ChangeAttributeTypeRequest",
          "description": null,
          "fields": null,
          "inputFields": [
            {
              "name": "clientMutationId",
              "description": null,
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "defaultValue": null
            },
            {
              "name": "kind",
              "description": null,
              "type": {
                "kind": "ENUM",
                "name": "AttributeKind",
                "ofType": null
              },
              "defaultValue": null
            }]
    }
```

If you don' send the enum value in the mutation input you get the following stacktrace:

```
java.lang.NullPointerException
	at graphql.schema.GraphQLEnumType.getValueByName(GraphQLEnumType.java:43)
	at graphql.schema.GraphQLEnumType.access$100(GraphQLEnumType.java:14)
	at graphql.schema.GraphQLEnumType$1.parseValue(GraphQLEnumType.java:28)
	at graphql.execution.ValuesResolver.coerceValueForEnum(ValuesResolver.java:96)
	at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:70)
	at graphql.execution.ValuesResolver.coerceValueForInputObjectField(ValuesResolver.java:84)
	at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:74)
	at graphql.execution.ValuesResolver.getVariableValue(ValuesResolver.java:59)
	at graphql.execution.ValuesResolver.getVariableValues(ValuesResolver.java:16)
	at graphql.execution.ExecutionContextBuilder.build(ExecutionContextBuilder.java:55)
	at graphql.execution.Execution.execute(Execution.java:32)
	at graphql.GraphQL.execute(GraphQL.java:78)
	at graphql.GraphQL.execute(GraphQL.java:55)
```

**Comment by andimarek** [comment]
Please try again with the latest version ... this should be fixed now.

**Comment by andimarek** [comment]
Closing, because it should be fixed. Please reopen if it's not working for you.

**Comment by andimarek** [comment]
Closing, because it should be fixed. Please reopen if it's not working for you.
