### ISSUE TITLE
GraphQLTypeReference should implement GraphQLUnmodifiedType?

### ISSUE THREAD

**Issue by Hellblazer** [andimarek/graphql-java#9]
I have a schema that uses GraphQLTypeReference for the usual reasons.  When I go to execute a query against that schema that references a field that does not exist, I see:

```
java.lang.ClassCastException: graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLUnmodifiedType
	at graphql.schema.SchemaUtil.getUnmodifiedType(SchemaUtil.java:33)
	at graphql.schema.SchemaUtil.isLeafType(SchemaUtil.java:15)
	at graphql.validation.rules.ScalarLeafs.checkField(ScalarLeafs.java:21)
	at graphql.validation.RulesVisitor.checkField(RulesVisitor.java:92)
	at graphql.validation.RulesVisitor.enter(RulesVisitor.java:51)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:19)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
	at graphql.validation.LanguageTraversal.traverse(LanguageTraversal.java:14)
	at graphql.validation.Validator.validateDocument(Validator.java:20)
	at graphql.GraphQL.execute(GraphQL.java:66)
	at graphql.GraphQL.execute(GraphQL.java:50)
	at graphql.GraphQL.execute(GraphQL.java:42)
```
I'm using version 1.2 from the maven repo.  I cloned the current state of master, built that, and get the same error.

What's particularly odd is that this is intermittent.  I can run sometimes the same test with no changes and immediately after failing it will succeed.  So I'm guessing there is some hash ordering diffs between runs that cause this to occasionally work.

So...  Is GraphQLTypeReference supposed to implement GraphQLUnmodifiedType, or am I doing something wrong with my GraphQLTypeReferences?

Thanks.  This is a wonderful library.

**Comment by Hellblazer** [comment]
So, this is due to my misunderstanding types and references in the top level schema.  In my schema generation, I believe I had multiple instances of the type I'm referencing.  Not good, I'm sure.  The randomness was due to my traversal and whether I emitted a concrete type, or a reference type in the given field definition based on lookup order from the db.  Not sure why I hit this class cast exception, but it was clearly due to me building the types and references between them incorrectly.
